# Generated by Django 6.0.6 on 2026-07-04 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание проекта')),
                ('model_file', models.FileField(upload_to='models/', verbose_name='Файл 3D-модели (.gltf/.glb)')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_projects', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Студенческий проект',
                'verbose_name_plural': 'Студенческие проекты',
            },
        ),
    ]
