# Generated by Django 6.0.6 on 2026-07-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'Педагог'), ('STUDENT', 'Студент')], default='STUDENT', max_length=10, verbose_name='Роль'),
        ),
    ]
