# Generated by Django 6.0.6 on 2026-07-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='academic_group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Учебная группа'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Кафедра'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='major',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Направление обучения'),
        ),
    ]
