"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
# ПОДГОТОВКА К ОБЛАКУ: Импортируем инструменты для чтения переменных окружения и БД
from decouple import config
import dj_database_url



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# ПОДГОТОВКА К ОБЛАКУ: Секретный ключ теперь берется из окружения сервера
SECRET_KEY = config('DJANGO_SECRET_KEY', default="django-insecure-(&r4r!@4m*dl^bwdo4g)h+v+3ba=ck2gx(0^@_@vsydhaj%rr^")

# ПОДГОТОВКА К ОБЛАКУ: На проде DEBUG всегда должен быть False
DEBUG = config('DEBUG', default=True, cast=bool)

# ПОДГОТОВКА К ОБЛАКУ: Сюда пишем домены (например: platform.ru, myplatform.amvera.ru) через запятую
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=lambda v: [s.strip() for s in v.split(',') if s.strip()])


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    # ПОДГОТОВКА К ОБЛАКУ: Добавляем storages для связи с S3 (установить: pip install django-storages boto3)
    'storages',
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "accounts",
    'projects',
    "allauth.socialaccount",
    'django_extensions',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # ПОДГОТОВКА К ОБЛАКУ: WhiteNoise для раздачи CSS/JS напрямую через Python/Gunicorn без Nginx
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    #'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Указываем Django искать шаблоны в нашей глобальной папке
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# ПОДГОТОВКА К ОБЛАКУ: Если в облаке задана DATABASE_URL, используем PostgreSQL/MySQL, иначе — локальный sqlite3
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"

# Указываем Django точный путь к вашей корневой папке static
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Папка, куда Django будет собирать всю статику при деплое (нужна для работы AppDirectoriesFinder)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# ПОДГОТОВКА К ОБЛАКУ: Настройка S3-хранилища для тяжелых 3D-моделей (Media-файлы)
# На локальной машине (DEBUG=True) файлы будут сохраняться на диск, в облаке — улетать в S3 бакет.
USE_S3 = config('USE_S3', default=False, cast=bool)

if USE_S3:
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = config('AWS_S3_ENDPOINT_URL')  # Важно для Yandex/Selectel/VK Cloud
    AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default=None)
    
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    AWS_QUERYSTRING_AUTH = False  # Отключает генерацию временных токенов для ссылок (чтобы ссылки на 3D были постоянными)
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# in boilerplate/config/settings.py
# all auth settings

SITE_ID = 1  # all-auth supports multiple sites

# Хак для Serverless: динамически подставляем ID сайта, если база данных пустая
def get_site_id():
    return 1


AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # this how admins will log in to the admin site
    "allauth.account.auth_backends.AuthenticationBackend",  # this how users log in
]
# Вместо фиксированной страницы отправляем пользователя на наш умный фильтр ролей
LOGIN_REDIRECT_URL = 'dashboard_redirect'

LOGOUT_REDIRECT_URL = "home"  # change to desired url name
ACCOUNT_SESSION_REMEMBER = 'always'  # remember user via sessions
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False  # preferred UX
ACCOUNT_USERNAME_REQUIRED = False  # preferred UX
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED = True  # required for email authentication
ACCOUNT_UNIQUE_EMAIL = True  # required for email authentication
ACCOUNT_EMAIL_VERIFICATION = "optional"  # can use as a welcome email as well
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 5
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 86400


# ПОДГОТОВКА К ОБЛАКУ: Включаем HTTPS протокол только для продакшена
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "http" if DEBUG else "https"

AUTH_USER_MODEL = 'accounts.CustomUser'

# ПОДГОТОВКА К ОБЛАКУ: На проде отправляем почту через реальный SMTP сервер
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = config('EMAIL_HOST')
    EMAIL_PORT = config('EMAIL_PORT', cast=int)
    EMAIL_HOST_USER = config('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
    EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)

# ПОДГОТОВКА К ОБЛАКУ: Настройки безопасности для HTTPS (включаются только на проде)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True



# Пути к кастомным формам
ACCOUNT_FORMS = {
    'signup': 'accounts.forms.CustomSignupForm',
    'login': 'accounts.forms.CustomLoginForm',
}

# Храним сессии в зашифрованных Cookie, чтобы не вылетало из админки в Serverless
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"

JAZZMIN_SETTINGS = {
    "site_title": "Панель 3D",
    "site_header": "Администрация",
    "site_brand": "Управление",
    "welcome_sign": "Авторизация",
    "copyright": "3D платформа",
    "show_ui_builder": False,
    "search_model": ["accounts.CustomUser"],
    "user_avatar": None,
    
    # ВОЗВРАЩАЕМ КОРРЕКТНЫЙ РЕЖИМ СВИТЧА:
    "theme_cls": "theme-switch", 
    
    "topmenu_links": [
        {"name": "Перейти на сайт", "url": "home", "permissions": ["accounts.view_customuser"]}, 
        # Убрали дублирующую текстовую кнопку-ссылку, так как теперь заработает нативная иконка в углу
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "icons": {
        "auth": "fas fa-users-cog",
        "accounts.customuser": "fas fa-user",  
        "auth.Group": "fas fa-users",
        "projects.studentproject": "fas fa-cube", 
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    
    # ИСПРАВЛЕНИЕ БАГА С ФОНОМ «Управление»:
    # Меняем "navbar-dark bg-dark" на прозрачно-темный класс. 
    # Это уберет уродливый обрезающийся прямоугольник из левого верхнего угла!
    "brand_colour": "navbar-dark bg-transparent",      
    
    "accent": "accent-dark",                     
    "navbar": "navbar-light bg-white",           
    "no_navbar_border": True,                    
    "navbar_fixed": False,
    "layout_options": ["sidebar_fixed"],
    "sidebar": "sidebar-light-white",            
    
    # ИСПРАВЛЕНИЕ НЕРАБОЧЕЙ КНОПКИ ТЕМЫ:
    # Вместо "default" ставим тему "cosmo". 
    # Она идеально поддерживает черно-белый стиль и полностью разблокирует JS-код переключения тем!
    "theme": "cosmo",                           
    "default_theme_mode": "auto",                
    
    "button_classes": {
        "primary": "btn-dark",                   
        "secondary": "btn-outline-dark",         
        "info": "btn-dark",
        "warning": "btn-secondary",
        "danger": "btn-danger",                  
        "success": "btn-dark"
    }
}