"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-(&r4r!@4m*dl^bwdo4g)h+v+3ba=ck2gx(0^@_@vsydhaj%rr^"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "accounts",
    'projects',
    "allauth.socialaccount",
    'django_extensions',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Указываем Django искать шаблоны в нашей глобальной папке
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"

# Указываем Django точный путь к вашей корневой папке static
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Папка, куда Django будет собирать всю статику при деплое (нужна для работы AppDirectoriesFinder)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# in boilerplate/config/settings.py
# all auth settings

SITE_ID = 1  # all-auth supports multiple sites


AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # this how admins will log in to the admin site
    "allauth.account.auth_backends.AuthenticationBackend",  # this how users log in
]
# Вместо фиксированной страницы отправляем пользователя на наш умный фильтр ролей
LOGIN_REDIRECT_URL = 'dashboard_redirect'

LOGOUT_REDIRECT_URL = "home"  # change to desired url name
ACCOUNT_SESSION_REMEMBER = True  # remember user via sessions
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False  # preferred UX
ACCOUNT_USERNAME_REQUIRED = False  # preferred UX
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED = True  # required for email authentication
ACCOUNT_UNIQUE_EMAIL = True  # required for email authentication
ACCOUNT_EMAIL_VERIFICATION = "optional"  # can use as a welcome email as well
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 5
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 86400
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"
AUTH_USER_MODEL = "accounts.CustomUser"

# email
# email will go to console for now, need to change in production
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTH_USER_MODEL = 'accounts.CustomUser'

# Пути к кастомным формам
ACCOUNT_FORMS = {
    'signup': 'accounts.forms.CustomSignupForm',
    'login': 'accounts.forms.CustomLoginForm',
}

JAZZMIN_SETTINGS = {
    "site_title": "Панель 3D",
    "site_header": "Администрация",
    "site_brand": "Управление",
    "welcome_sign": "Авторизация",
    "copyright": "3D платформа",
    "show_ui_builder": False,
    "search_model": ["accounts.CustomUser"],
    "user_avatar": None,
    
    # ВОЗВРАЩАЕМ КОРРЕКТНЫЙ РЕЖИМ СВИТЧА:
    "theme_cls": "theme-switch", 
    
    "topmenu_links": [
        {"name": "Перейти на сайт", "url": "home", "permissions": ["accounts.view_customuser"]}, 
        # Убрали дублирующую текстовую кнопку-ссылку, так как теперь заработает нативная иконка в углу
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "icons": {
        "auth": "fas fa-users-cog",
        "accounts.customuser": "fas fa-user",  
        "auth.Group": "fas fa-users",
        "projects.studentproject": "fas fa-cube", 
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    
    # ИСПРАВЛЕНИЕ БАГА С ФОНОМ «Управление»:
    # Меняем "navbar-dark bg-dark" на прозрачно-темный класс. 
    # Это уберет уродливый обрезающийся прямоугольник из левого верхнего угла!
    "brand_colour": "navbar-dark bg-transparent",      
    
    "accent": "accent-dark",                     
    "navbar": "navbar-light bg-white",           
    "no_navbar_border": True,                    
    "navbar_fixed": False,
    "layout_options": ["sidebar_fixed"],
    "sidebar": "sidebar-light-white",            
    
    # ИСПРАВЛЕНИЕ НЕРАБОЧЕЙ КНОПКИ ТЕМЫ:
    # Вместо "default" ставим тему "cosmo". 
    # Она идеально поддерживает черно-белый стиль и полностью разблокирует JS-код переключения тем!
    "theme": "cosmo",                           
    "default_theme_mode": "auto",                
    
    "button_classes": {
        "primary": "btn-dark",                   
        "secondary": "btn-outline-dark",         
        "info": "btn-dark",
        "warning": "btn-secondary",
        "danger": "btn-danger",                  
        "success": "btn-dark"
    }
}